#Building
FROM gcc:latest

RUN apt-get update && apt-get install -y \
    libncurses5-dev\
    libncursesw5-dev\
    nano\
    iproute2

#Docker-Arbeitsverzeichnis
WORKDIR /usr/src/app
COPY . . 

#Binary erstellen
RUN gcc -o sip-manipulator main.c manipulator-function.c log.c -lncurses

COPY hmr.txt config.txt /usr/src/app/

CMD ["sleep", "infinity"]

