apiVersion: v1
kind: Service
metadata:
  name: sip-manipulator-service-maintenance
spec:
  selector:
    app: sip-manipulator-server
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 30000
    nodePort: 30081
  type: NodePort
