apiVersion: v1
kind: Service
metadata:
  name: sip-manipulator-service
spec:
  selector:
    app: sip-manipulator-server
  ports:
  - protocol: TCP
    port: 5060
    targetPort: 5060
    nodePort: 30080
  type: NodePort
